//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticle
    {
        public int ArticleID { get; set; }
        public string Article { get; set; }
        public string Code { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> Stored { get; set; }
    }
}
